---
# Project Information
site_name: RainbowDrinkingGame
site_author: Matti Kaupenjohann
site_description: A small pyqt app for a drinking game. You need Rainbowsix Siege to play accurate ;).

# Repository information
repo_name: makanu/rainbowdrinkinggame
repo_url: https://github.com/makanu/rainbowdrinkinggame
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 Matti Kaupenjohann

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/makanu
      name: makanu on GitHub

# Page tree
nav:
  - Home: 
    - Introduction: index.md
  - Rules:
    - Basic: rules/basic.md
  - Packages:
    - rainbowdrinkinggame: packages/rainbowdrinkinggame.md
    - tests: packages/tests.md
