---
name: Code Quality Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os : [ubuntu-latest]
        python: [3.7]
    env:
      DISPLAY: ':99.0'
    steps:
      - name: get repo
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: setup ${{ matrix.os }}
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Unit & Coverage test with pytest
        run: poetry run pytest
      
      - name: Check style with pylint
        run: poetry run pylint rainbowdrinkinggame/ tests/
      - name: Check format with black
        run: poetry run black --check rainbowdrinkinggame/ tests/
      - name: Check type hinting with mypy
        run: poetry run mypy --strict --config-file=mypy.ini rainbowdrinkinggame/
      
